import type { PresetScenario } from './types';

/**
 * 28 pre-computed geopolitical scenarios for FateMap.
 * Categories: military (5), trade (3), energy (3), climate (4),
 * health (2), political (5), economic (2), technology (4).
 *
 * Each scenario contains a full SimulationResult with
 * epicenter, 5-15 country impacts, 3-8 city impacts,
 * activated relationship IDs, and bilingual summaries.
 */
export const SCENARIOS: PresetScenario[] = [
  // ═══════════════════════════════════════════════════════════════
  // MILITARY (5)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'taiwan-strait-crisis',
    name: 'Taiwan Strait Military Crisis',
    nameCn: '台湾海峡军事危机',
    category: 'military',
    description: 'Mainland China initiates a military blockade of Taiwan, triggering global semiconductor and security crisis.',
    descriptionZh: '中国大陆发起对台湾的军事封锁，引发全球半导体和安全危机。',
    eventText: 'What if Mainland China initiates a military blockade of Taiwan?',
    keywords: ['taiwan', 'strait', 'blockade', 'china', 'military', '台湾', '海峡', '封锁', '军事'],
    result: {
      event: 'Mainland China initiates a military blockade of Taiwan',
      timestamp: '2026-01-15T00:00:00Z',
      epicenter: { countryId: 'TWN', coordinates: [120.96, 23.70] },
      countryImpacts: [
        { countryId: 'TWN', severity: 'critical', direction: 'negative', impactPercent: -50, reason: 'Direct military blockade target; economy paralyzed', reasonZh: '直接军事封锁目标；经济瘫痪' },
        { countryId: 'CHN', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Mainland initiator faces global sanctions and trade isolation', reasonZh: '大陆发起方面临全球制裁和贸易孤立' },
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Security treaty obligations; semiconductor supply cut', reasonZh: '安全条约义务；半导体供应中断' },
        { countryId: 'JPN', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Adjacent security threat; trade route disruption', reasonZh: '邻近安全威胁；贸易航线中断' },
        { countryId: 'KOR', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Regional instability; semiconductor competition', reasonZh: '区域不稳定；半导体竞争' },
        { countryId: 'SGP', severity: 'medium', direction: 'negative', impactPercent: -15, reason: 'Shipping lane disruption through South China Sea', reasonZh: '南海航运通道中断' },
        { countryId: 'AUS', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'AUKUS ally; trade with mainland severed', reasonZh: 'AUKUS盟友；对大陆贸易中断' },
        { countryId: 'DEU', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Semiconductor shortage hits auto industry', reasonZh: '半导体短缺冲击汽车工业' },
        { countryId: 'IND', severity: 'low', direction: 'mixed', impactPercent: -5, reason: 'Manufacturing shift opportunity but regional instability', reasonZh: '制造业转移机遇但区域不稳定' },
        { countryId: 'VNM', severity: 'medium', direction: 'mixed', impactPercent: -8, reason: 'Supply chain beneficiary but geographic proximity risk', reasonZh: '供应链受益但地理邻近风险' },
      ],
      cityImpacts: [
        { cityId: 'taipei', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'kaohsiung', severity: 'critical', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'shanghai', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'tokyo', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'singapore', severity: 'medium', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'san-francisco', severity: 'high', direction: 'negative', impactType: 'supply_shortage' },
      ],
      activatedRelationships: [
        'USA-TWN-supply_chain', 'CHN-TWN-supply_chain', 'USA-TWN-political',
        'CHN-TWN-political', 'USA-JPN-military_alliance', 'USA-KOR-military_alliance',
        'USA-AUS-military_alliance', 'CHN-JPN-trade', 'CHN-KOR-trade', 'CHN-SGP-trade',
        'JPN-TWN-supply_chain', 'KOR-TWN-supply_chain',
      ],
      summary: 'A mainland Chinese military blockade of Taiwan would trigger the most severe geopolitical crisis since WWII, disrupting global semiconductor supply (TSMC produces 60% of world chips), activating US-Japan-Australia military alliances, and potentially reshaping the entire Indo-Pacific security order.',
      summaryZh: '中国大陆对台湾的军事封锁将引发二战以来最严重的地缘政治危机，扰乱全球半导体供应（台积电生产全球60%的芯片），激活美日澳军事同盟，并可能重塑整个印太安全秩序。',
    },
  },
  {
    id: 'korean-peninsula-conflict',
    name: 'Korean Peninsula Military Conflict',
    nameCn: '朝鲜半岛军事冲突',
    category: 'military',
    description: 'North Korea launches a military provocation against South Korea.',
    descriptionZh: '朝鲜对韩国发起军事挑衅。',
    eventText: 'What if North Korea launches a military strike on South Korea?',
    keywords: ['korea', 'north korea', 'pyongyang', 'korean', 'peninsula', '朝鲜', '韩国', '半岛', '军事'],
    result: {
      event: 'North Korea launches a military strike on South Korea',
      timestamp: '2026-02-01T00:00:00Z',
      epicenter: { countryId: 'PRK', coordinates: [127.51, 40.34] },
      countryImpacts: [
        { countryId: 'PRK', severity: 'critical', direction: 'negative', impactPercent: -50, reason: 'Regime faces total international isolation and retaliation', reasonZh: '政权面临全面国际孤立和报复' },
        { countryId: 'KOR', severity: 'critical', direction: 'negative', impactPercent: -45, reason: 'Direct military target; Seoul in artillery range', reasonZh: '直接军事目标；首尔在炮火范围内' },
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Treaty ally; 28,500 troops stationed in South Korea', reasonZh: '条约盟友；28,500名驻韩美军' },
        { countryId: 'JPN', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Regional security threat; potential missile target', reasonZh: '区域安全威胁；潜在导弹目标' },
        { countryId: 'CHN', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Buffer state destabilized; refugee crisis on border', reasonZh: '缓冲国动荡；边境难民危机' },
        { countryId: 'RUS', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Border proximity; diplomatic pressure', reasonZh: '边境邻近；外交压力' },
        { countryId: 'TWN', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Regional instability raises invasion fears', reasonZh: '区域不稳定加剧入侵恐惧' },
        { countryId: 'AUS', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Alliance obligations in Indo-Pacific', reasonZh: '印太地区同盟义务' },
      ],
      cityImpacts: [
        { cityId: 'seoul', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'pyongyang', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'tokyo', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'beijing', severity: 'high', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'busan', severity: 'high', direction: 'negative', impactType: 'military_threat' },
      ],
      activatedRelationships: [
        'KOR-PRK-political', 'KOR-PRK-geographic_proximity', 'USA-KOR-military_alliance',
        'USA-JPN-military_alliance', 'CHN-PRK-military_alliance', 'CHN-PRK-political',
        'CHN-PRK-geographic_proximity',
      ],
      summary: 'A North Korean military strike on South Korea would put 25 million Seoul residents in immediate danger, activate the US-ROK mutual defense treaty, and risk drawing China into a conflict to protect its buffer state — potentially the most dangerous flashpoint in East Asia.',
      summaryZh: '朝鲜对韩国的军事打击将使2500万首尔居民面临直接危险，激活美韩共同防御条约，并可能将中国拖入保护其缓冲国的冲突——这可能是东亚最危险的热点。',
    },
  },
  {
    id: 'india-pakistan-escalation',
    name: 'India-Pakistan Border Escalation',
    nameCn: '印巴边境冲突升级',
    category: 'military',
    description: 'Military escalation between India and Pakistan along the Line of Control.',
    descriptionZh: '印度和巴基斯坦沿控制线发生军事升级。',
    eventText: 'What if India and Pakistan have a military confrontation along the Kashmir border?',
    keywords: ['india', 'pakistan', 'kashmir', 'border', 'nuclear', '印度', '巴基斯坦', '克什米尔', '边境'],
    result: {
      event: 'India-Pakistan military confrontation along Kashmir border',
      timestamp: '2026-03-01T00:00:00Z',
      epicenter: { countryId: 'IND', coordinates: [76.0, 34.0] },
      countryImpacts: [
        { countryId: 'IND', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Direct combatant; nuclear escalation risk', reasonZh: '直接参战方；核升级风险' },
        { countryId: 'PAK', severity: 'critical', direction: 'negative', impactPercent: -40, reason: 'Direct combatant; economic collapse risk', reasonZh: '直接参战方；经济崩溃风险' },
        { countryId: 'CHN', severity: 'medium', direction: 'mixed', impactPercent: -8, reason: 'Pakistan ally; border concerns in Aksai Chin', reasonZh: '巴基斯坦盟友；阿克赛钦边境担忧' },
        { countryId: 'USA', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Diplomatic crisis; IT outsourcing disruption', reasonZh: '外交危机；IT外包中断' },
        { countryId: 'BGD', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Refugee spillover; trade disruption', reasonZh: '难民溢出；贸易中断' },
        { countryId: 'SAU', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Large diaspora in both countries; oil demand shift', reasonZh: '两国大量侨民；石油需求变动' },
        { countryId: 'ARE', severity: 'low', direction: 'negative', impactPercent: -6, reason: 'Significant Indian and Pakistani workforce', reasonZh: '大量印巴劳动力' },
        { countryId: 'GBR', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Commonwealth ties; large diaspora', reasonZh: '英联邦关系；大量侨民' },
      ],
      cityImpacts: [
        { cityId: 'new-delhi', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'islamabad', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'karachi', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'mumbai', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'dhaka', severity: 'medium', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'dubai', severity: 'medium', direction: 'negative', impactType: 'trade_disruption' },
      ],
      activatedRelationships: [
        'IND-PAK-political', 'PAK-IND-geographic_proximity', 'PAK-CHN-military_alliance',
        'IND-RUS-military_alliance', 'USA-IND-trade', 'IND-BGD-geographic_proximity',
        'IND-ARE-trade', 'IND-SAU-energy_dependency',
      ],
      summary: 'An India-Pakistan military confrontation in Kashmir would be uniquely dangerous as both nations possess nuclear weapons. The conflict could disrupt $200B+ in global IT services, trigger refugee crises in Bangladesh, and force China and the US into opposing diplomatic camps.',
      summaryZh: '印巴在克什米尔的军事对抗将极其危险，因为两国都拥有核武器。冲突可能扰乱超过2000亿美元的全球IT服务，引发孟加拉国难民危机，并迫使中美进入对立的外交阵营。',
    },
  },
  {
    id: 'nato-russia-confrontation',
    name: 'NATO-Russia Direct Confrontation',
    nameCn: '北约-俄罗斯直接对抗',
    category: 'military',
    description: 'NATO and Russia engage in direct military confrontation in Eastern Europe.',
    descriptionZh: '北约和俄罗斯在东欧发生直接军事对抗。',
    eventText: 'What if NATO and Russia have a direct military confrontation?',
    keywords: ['nato', 'russia', 'confrontation', 'europe', 'nuclear', '北约', '俄罗斯', '对抗', '欧洲'],
    result: {
      event: 'NATO-Russia direct military confrontation in Eastern Europe',
      timestamp: '2026-04-01T00:00:00Z',
      epicenter: { countryId: 'POL', coordinates: [19.15, 51.92] },
      countryImpacts: [
        { countryId: 'RUS', severity: 'critical', direction: 'negative', impactPercent: -45, reason: 'Direct combatant facing NATO full force', reasonZh: '直接面对北约全力的参战方' },
        { countryId: 'POL', severity: 'critical', direction: 'negative', impactPercent: -40, reason: 'Front-line NATO state; likely theater of conflict', reasonZh: '北约前线国家；可能的冲突战区' },
        { countryId: 'UKR', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Caught between warring parties', reasonZh: '夹在交战双方之间' },
        { countryId: 'DEU', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Major NATO logistics hub; energy crisis', reasonZh: '北约主要后勤枢纽；能源危机' },
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'NATO leader; massive military commitment', reasonZh: '北约领导者；大规模军事投入' },
        { countryId: 'GBR', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Key NATO ally; nuclear deterrence activated', reasonZh: '关键北约盟友；核威慑激活' },
        { countryId: 'FRA', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Nuclear power; EU defense mobilization', reasonZh: '核大国；欧盟防务动员' },
        { countryId: 'NOR', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Arctic border with Russia; NATO flank', reasonZh: '与俄罗斯北极边境；北约侧翼' },
        { countryId: 'TUR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Controls straits; complex Russia relationship', reasonZh: '控制海峡；与俄罗斯关系复杂' },
        { countryId: 'CHN', severity: 'medium', direction: 'mixed', impactPercent: -8, reason: 'Strategic partner of Russia; opportunity and risk', reasonZh: '俄罗斯战略伙伴；机遇与风险并存' },
      ],
      cityImpacts: [
        { cityId: 'warsaw', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'moscow', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'berlin', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'london', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'kyiv', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'oslo', severity: 'medium', direction: 'negative', impactType: 'military_threat' },
      ],
      activatedRelationships: [
        'RUS-UKR-political', 'RUS-UKR-geographic_proximity', 'DEU-RUS-energy_dependency',
        'USA-DEU-military_alliance', 'USA-GBR-military_alliance', 'USA-FRA-military_alliance',
        'USA-POL-military_alliance', 'USA-NOR-military_alliance', 'USA-TUR-military_alliance',
        'CHN-RUS-military_alliance', 'CHN-RUS-political', 'FRA-DEU-military_alliance',
        'GBR-FRA-military_alliance',
      ],
      summary: 'A direct NATO-Russia confrontation would be the most dangerous military crisis since the Cuban Missile Crisis, with both sides possessing thousands of nuclear warheads. European energy markets would collapse, global financial markets would crash, and the risk of nuclear escalation would be unprecedented.',
      summaryZh: '北约与俄罗斯的直接对抗将是自古巴导弹危机以来最危险的军事危机，双方拥有数千枚核弹头。欧洲能源市场将崩溃，全球金融市场将暴跌，核升级的风险将是前所未有的。',
    },
  },
  {
    id: 'south-china-sea-clash',
    name: 'South China Sea Territorial Clash',
    nameCn: '南海领土冲突',
    category: 'military',
    description: 'Armed confrontation between China and Philippines in the South China Sea.',
    descriptionZh: '中国和菲律宾在南海发生武装对抗。',
    eventText: 'What if China and the Philippines clash militarily in the South China Sea?',
    keywords: ['south china sea', 'philippines', 'spratlys', 'islands', '南海', '菲律宾', '南沙', '岛礁'],
    result: {
      event: 'China-Philippines armed clash in the South China Sea',
      timestamp: '2026-05-01T00:00:00Z',
      epicenter: { countryId: 'PHL', coordinates: [116.0, 12.0] },
      countryImpacts: [
        { countryId: 'PHL', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Direct confrontation with major military power', reasonZh: '与军事大国直接对抗' },
        { countryId: 'CHN', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'International condemnation; trade disruption', reasonZh: '国际谴责；贸易中断' },
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Mutual Defense Treaty with Philippines activated', reasonZh: '与菲律宾的共同防御条约激活' },
        { countryId: 'VNM', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Competing territorial claims; shipping disruption', reasonZh: '领土争端竞争；航运中断' },
        { countryId: 'JPN', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Critical shipping lanes threatened', reasonZh: '关键航运通道受威胁' },
        { countryId: 'SGP', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Major shipping hub disrupted', reasonZh: '主要航运枢纽中断' },
        { countryId: 'MYS', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Overlapping territorial claims', reasonZh: '重叠的领土主张' },
        { countryId: 'IDN', severity: 'low', direction: 'negative', impactPercent: -8, reason: 'EEZ concerns; regional instability', reasonZh: '专属经济区担忧；区域不稳定' },
        { countryId: 'AUS', severity: 'low', direction: 'negative', impactPercent: -6, reason: 'Indo-Pacific alliance obligations', reasonZh: '印太同盟义务' },
        { countryId: 'KOR', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Trade route disruption', reasonZh: '贸易航线中断' },
      ],
      cityImpacts: [
        { cityId: 'manila', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'singapore', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'ho-chi-minh', severity: 'medium', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'hong-kong', severity: 'medium', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'tokyo', severity: 'medium', direction: 'negative', impactType: 'market_crash' },
      ],
      activatedRelationships: [
        'USA-PHL-military_alliance', 'CHN-VNM-geographic_proximity', 'CHN-SGP-trade',
        'CHN-MYS-trade', 'SGP-MYS-trade', 'SGP-IDN-trade', 'SGP-MYS-geographic_proximity',
        'IDN-MYS-geographic_proximity', 'USA-SGP-military_alliance',
      ],
      summary: 'A China-Philippines armed clash in the South China Sea would threaten $5.3 trillion in annual shipping trade, activate the US-Philippines Mutual Defense Treaty, and potentially draw Vietnam, Malaysia, and Indonesia into the dispute over overlapping territorial claims.',
      summaryZh: '中菲在南海的武装冲突将威胁每年5.3万亿美元的航运贸易，激活美菲共同防御条约，并可能将越南、马来西亚和印度尼西亚拖入重叠领土主张的争端。',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // TRADE (3)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'us-china-trade-war',
    name: 'US-China Full Trade War',
    nameCn: '中美全面贸易战',
    category: 'trade',
    description: 'US and China impose 100%+ tariffs on all bilateral trade.',
    descriptionZh: '中美对所有双边贸易征收100%以上关税。',
    eventText: 'What if the US and China impose 100% tariffs on all bilateral trade?',
    keywords: ['trade war', 'tariff', 'us china', 'sanctions', 'decoupling', '贸易战', '关税', '中美', '制裁', '脱钩'],
    result: {
      event: 'US-China full trade war with 100%+ tariffs',
      timestamp: '2026-01-01T00:00:00Z',
      epicenter: { countryId: 'USA', coordinates: [-98.58, 39.83] },
      countryImpacts: [
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Consumer prices surge; tech supply chain broken', reasonZh: '消费价格飙升；科技供应链断裂' },
        { countryId: 'CHN', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Export-dependent economy severely hit', reasonZh: '出口依赖型经济严重受创' },
        { countryId: 'VNM', severity: 'high', direction: 'positive', impactPercent: 20, reason: 'Manufacturing shifts from China', reasonZh: '制造业从中国转移' },
        { countryId: 'MEX', severity: 'high', direction: 'positive', impactPercent: 18, reason: 'Nearshoring boom from US companies', reasonZh: '美国企业近岸外包繁荣' },
        { countryId: 'IND', severity: 'medium', direction: 'positive', impactPercent: 15, reason: 'Alternative manufacturing destination', reasonZh: '替代制造业目的地' },
        { countryId: 'JPN', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Caught between trading partners', reasonZh: '夹在贸易伙伴之间' },
        { countryId: 'KOR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Supply chain disruption', reasonZh: '供应链中断' },
        { countryId: 'DEU', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'China market access threatened', reasonZh: '中国市场准入受威胁' },
        { countryId: 'SGP', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Trade hub volumes decline', reasonZh: '贸易枢纽交易量下降' },
        { countryId: 'AUS', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Commodity exports to China hit', reasonZh: '对华大宗商品出口受创' },
        { countryId: 'TWN', severity: 'medium', direction: 'mixed', impactPercent: -8, reason: 'Semiconductor geopolitics intensify', reasonZh: '半导体地缘政治加剧' },
        { countryId: 'BRA', severity: 'low', direction: 'positive', impactPercent: 8, reason: 'Soy and commodity demand shift', reasonZh: '大豆和商品需求转移' },
      ],
      cityImpacts: [
        { cityId: 'shanghai', severity: 'critical', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'shenzhen', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'los-angeles', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'ho-chi-minh', severity: 'high', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'mexico-city', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'new-york', severity: 'high', direction: 'negative', impactType: 'market_crash' },
      ],
      activatedRelationships: [
        'USA-CHN-trade', 'USA-CHN-supply_chain', 'USA-CHN-political',
        'USA-VNM-supply_chain', 'USA-MEX-supply_chain', 'USA-MEX-trade',
        'CHN-VNM-supply_chain', 'USA-IND-supply_chain', 'USA-IND-trade',
        'CHN-AUS-trade', 'CHN-JPN-trade', 'CHN-KOR-trade',
      ],
      summary: 'A full US-China trade war with 100%+ tariffs would fragment the $700B bilateral trade relationship, sending shockwaves through global supply chains. Vietnam, Mexico, and India would be the biggest beneficiaries of manufacturing relocation, while consumer prices in both countries would spike.',
      summaryZh: '中美全面贸易战将分裂7000亿美元的双边贸易关系，冲击全球供应链。越南、墨西哥和印度将成为制造业转移的最大受益者，而两国消费价格都将飙升。',
    },
  },
  {
    id: 'suez-canal-closure',
    name: 'Suez Canal Closure',
    nameCn: '苏伊士运河关闭',
    category: 'trade',
    description: 'Suez Canal blocked or closed, halting 12% of global trade.',
    descriptionZh: '苏伊士运河阻塞或关闭，中断全球12%的贸易。',
    eventText: 'What if the Suez Canal is blocked or permanently closed?',
    keywords: ['suez', 'canal', 'egypt', 'shipping', 'blocked', '苏伊士', '运河', '埃及', '航运', '堵塞'],
    result: {
      event: 'Suez Canal closure halting global shipping',
      timestamp: '2026-02-15T00:00:00Z',
      epicenter: { countryId: 'EGY', coordinates: [32.55, 29.97] },
      countryImpacts: [
        { countryId: 'EGY', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Canal revenue ($9B/yr) eliminated; strategic leverage lost', reasonZh: '运河收入（90亿美元/年）消失；战略杠杆丧失' },
        { countryId: 'NLD', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Rotterdam port traffic severely disrupted', reasonZh: '鹿特丹港口交通严重中断' },
        { countryId: 'DEU', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Export/import routes via Mediterranean cut', reasonZh: '经地中海的进出口路线中断' },
        { countryId: 'ITA', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Mediterranean trade hub disrupted', reasonZh: '地中海贸易枢纽中断' },
        { countryId: 'SAU', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Oil export route to Europe blocked', reasonZh: '对欧石油出口路线中断' },
        { countryId: 'CHN', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Belt and Road shipping route disrupted', reasonZh: '一带一路航运路线中断' },
        { countryId: 'GBR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Import costs rise; longer shipping routes', reasonZh: '进口成本上升；更长的航运路线' },
        { countryId: 'IND', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Europe trade route lengthened', reasonZh: '对欧贸易路线延长' },
        { countryId: 'SGP', severity: 'medium', direction: 'positive', impactPercent: 10, reason: 'Alternative routes may boost Asian hub traffic', reasonZh: '替代路线可能增加亚洲枢纽交通' },
        { countryId: 'ZAF', severity: 'low', direction: 'positive', impactPercent: 8, reason: 'Cape of Good Hope route gains traffic', reasonZh: '好望角路线交通增加' },
      ],
      cityImpacts: [
        { cityId: 'suez', severity: 'critical', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'cairo', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'rotterdam', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'hamburg', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'singapore', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'cape-town', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
      ],
      activatedRelationships: [
        'ISR-EGY-geographic_proximity', 'ISR-EGY-political', 'DEU-NLD-trade',
        'DEU-ITA-trade', 'CHN-SAU-energy_dependency', 'IND-SAU-energy_dependency',
        'JPN-SAU-energy_dependency', 'EGY-SAU-geographic_proximity', 'EGY-SAU-energy_dependency',
      ],
      summary: 'Closure of the Suez Canal would disrupt 12% of global trade and 30% of container shipping, adding 10-15 days to Europe-Asia routes via the Cape of Good Hope. Egypt would lose $9B in annual transit fees, while European ports and energy importers would face severe supply disruptions.',
      summaryZh: '苏伊士运河关闭将中断全球12%的贸易和30%的集装箱航运，经好望角的欧亚航线将增加10-15天。埃及将失去每年90亿美元的过境费，而欧洲港口和能源进口国将面临严重的供应中断。',
    },
  },
  {
    id: 'global-supply-chain-decoupling',
    name: 'Global Supply Chain Decoupling',
    nameCn: '全球供应链脱钩',
    category: 'trade',
    description: 'Major economies decouple supply chains, forming rival trade blocs.',
    descriptionZh: '主要经济体供应链脱钩，形成对立贸易集团。',
    eventText: 'What if the world splits into rival trade blocs with decoupled supply chains?',
    keywords: ['decoupling', 'supply chain', 'trade bloc', 'reshoring', 'friendshoring', '脱钩', '供应链', '贸易集团', '回流'],
    result: {
      event: 'Global supply chain decoupling into rival trade blocs',
      timestamp: '2026-03-15T00:00:00Z',
      epicenter: { countryId: 'CHN', coordinates: [104.20, 35.86] },
      countryImpacts: [
        { countryId: 'CHN', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Export markets shrink as West reshores', reasonZh: '西方回流导致出口市场萎缩' },
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Higher costs from domestic manufacturing transition', reasonZh: '国内制造业转型成本上升' },
        { countryId: 'VNM', severity: 'high', direction: 'positive', impactPercent: 25, reason: 'Friendshoring destination of choice', reasonZh: '友岸外包首选目的地' },
        { countryId: 'IND', severity: 'high', direction: 'positive', impactPercent: 22, reason: 'Alternative manufacturing powerhouse', reasonZh: '替代制造业强国' },
        { countryId: 'MEX', severity: 'high', direction: 'positive', impactPercent: 20, reason: 'US nearshoring hub', reasonZh: '美国近岸外包枢纽' },
        { countryId: 'DEU', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Industrial inputs become costlier', reasonZh: '工业投入品变得更贵' },
        { countryId: 'JPN', severity: 'medium', direction: 'mixed', impactPercent: -5, reason: 'Must choose bloc; losing China market access', reasonZh: '必须选边；失去中国市场准入' },
        { countryId: 'KOR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Semiconductor industry caught between blocs', reasonZh: '半导体产业夹在集团之间' },
        { countryId: 'SGP', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Trade hub volumes decline in bifurcated world', reasonZh: '二分世界中贸易枢纽交易量下降' },
        { countryId: 'IDN', severity: 'medium', direction: 'positive', impactPercent: 12, reason: 'Non-aligned nations gain manufacturing share', reasonZh: '不结盟国家获得制造业份额' },
      ],
      cityImpacts: [
        { cityId: 'guangzhou', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'shenzhen', severity: 'high', direction: 'negative', impactType: 'supply_shortage' },
        { cityId: 'ho-chi-minh', severity: 'high', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'mumbai', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'mexico-city', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'jakarta', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
      ],
      activatedRelationships: [
        'USA-CHN-supply_chain', 'USA-VNM-supply_chain', 'USA-MEX-supply_chain',
        'USA-IND-supply_chain', 'CHN-VNM-supply_chain', 'CHN-BGD-supply_chain',
        'CHN-IDN-supply_chain', 'CHN-MYS-supply_chain', 'DEU-CHN-supply_chain',
        'FRA-CHN-supply_chain', 'JPN-CHN-supply_chain', 'KOR-CHN-supply_chain',
      ],
      summary: 'A global supply chain decoupling would split the world into US-led and China-led trade blocs, raising manufacturing costs by 15-25% globally. Vietnam, India, and Mexico would emerge as the biggest winners, while China and Europe would face the steepest adjustments.',
      summaryZh: '全球供应链脱钩将世界分裂为美国主导和中国主导的贸易集团，全球制造成本上升15-25%。越南、印度和墨西哥将成为最大赢家，而中国和欧洲将面临最大调整。',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // ENERGY (3)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'hormuz-strait-blockade',
    name: 'Strait of Hormuz Blockade',
    nameCn: '霍尔木兹海峡封锁',
    category: 'energy',
    description: 'Iran blocks the Strait of Hormuz, choking 20% of global oil supply.',
    descriptionZh: '伊朗封锁霍尔木兹海峡，扼杀全球20%的石油供应。',
    eventText: 'What if Iran blocks the Strait of Hormuz?',
    keywords: ['hormuz', 'strait', 'iran', 'oil', 'blockade', '霍尔木兹', '海峡', '伊朗', '石油', '封锁'],
    result: {
      event: 'Iran blocks the Strait of Hormuz',
      timestamp: '2026-04-15T00:00:00Z',
      epicenter: { countryId: 'IRN', coordinates: [56.27, 27.18] },
      countryImpacts: [
        { countryId: 'IRN', severity: 'critical', direction: 'negative', impactPercent: -40, reason: 'Military retaliation risk; own exports blocked', reasonZh: '军事报复风险；自身出口被阻断' },
        { countryId: 'SAU', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Primary export route blocked', reasonZh: '主要出口路线被阻断' },
        { countryId: 'ARE', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Oil exports and trade hub paralyzed', reasonZh: '石油出口和贸易枢纽瘫痪' },
        { countryId: 'IRQ', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Southern oil exports cut off', reasonZh: '南部石油出口中断' },
        { countryId: 'JPN', severity: 'high', direction: 'negative', impactPercent: -20, reason: '80% of oil imports pass through Hormuz', reasonZh: '80%的石油进口经霍尔木兹' },
        { countryId: 'KOR', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Heavy dependence on Gulf oil', reasonZh: '严重依赖海湾石油' },
        { countryId: 'IND', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Major Gulf oil importer', reasonZh: '主要海湾石油进口国' },
        { countryId: 'CHN', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Largest Gulf oil buyer', reasonZh: '最大的海湾石油买家' },
        { countryId: 'USA', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Oil price spike despite domestic production', reasonZh: '尽管有国内生产但油价飙升' },
        { countryId: 'NOR', severity: 'low', direction: 'positive', impactPercent: 15, reason: 'Alternative oil/gas supplier; prices surge', reasonZh: '替代石油天然气供应商；价格飙升' },
      ],
      cityImpacts: [
        { cityId: 'bandar-abbas', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'dubai', severity: 'critical', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'riyadh', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'basra', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'tokyo', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'mumbai', severity: 'medium', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'oslo', severity: 'low', direction: 'positive', impactType: 'opportunity' },
      ],
      activatedRelationships: [
        'ISR-IRN-political', 'SAU-IRN-political', 'IRN-IRQ-geographic_proximity',
        'IRN-IRQ-political', 'JPN-SAU-energy_dependency', 'JPN-ARE-energy_dependency',
        'KOR-SAU-energy_dependency', 'CHN-SAU-energy_dependency', 'CHN-IRN-energy_dependency',
        'IND-SAU-energy_dependency', 'IND-IRN-energy_dependency', 'SAU-ARE-military_alliance',
        'SAU-ARE-geographic_proximity', 'USA-SAU-energy_dependency',
      ],
      summary: 'A Strait of Hormuz blockade would choke 20% of global oil supply and 25% of LNG, sending oil prices above $200/barrel. Japan and South Korea, which import 80%+ of their oil through Hormuz, would face immediate energy emergencies. Norway and non-Gulf producers would see windfall profits.',
      summaryZh: '霍尔木兹海峡封锁将扼杀全球20%的石油供应和25%的液化天然气，推动油价超过200美元/桶。日本和韩国80%以上的石油进口经霍尔木兹，将面临直接的能源紧急状态。挪威和非海湾产油国将获得意外利润。',
    },
  },
  {
    id: 'opec-production-collapse',
    name: 'OPEC+ Production Collapse',
    nameCn: 'OPEC+产量崩溃',
    category: 'energy',
    description: 'OPEC+ alliance fractures, causing uncontrolled oil market chaos.',
    descriptionZh: 'OPEC+联盟破裂，导致石油市场失控混乱。',
    eventText: 'What if OPEC+ collapses and members flood the market with cheap oil?',
    keywords: ['opec', 'oil', 'production', 'price war', 'saudi', '欧佩克', '石油', '产量', '价格战', '沙特'],
    result: {
      event: 'OPEC+ alliance collapse and oil price war',
      timestamp: '2026-05-15T00:00:00Z',
      epicenter: { countryId: 'SAU', coordinates: [45.08, 23.89] },
      countryImpacts: [
        { countryId: 'SAU', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Revenue crash despite production surge', reasonZh: '尽管增产但收入崩溃' },
        { countryId: 'RUS', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Budget depends on high oil; cannot compete on cost', reasonZh: '预算依赖高油价；无法在成本上竞争' },
        { countryId: 'IRN', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Oil revenue collapse under existing sanctions', reasonZh: '现有制裁下石油收入崩溃' },
        { countryId: 'VEN', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Economy entirely oil-dependent; collapse deepens', reasonZh: '经济完全依赖石油；崩溃加深' },
        { countryId: 'NGA', severity: 'high', direction: 'negative', impactPercent: -22, reason: 'Oil-dependent budget devastated', reasonZh: '依赖石油的预算被摧毁' },
        { countryId: 'NOR', severity: 'medium', direction: 'negative', impactPercent: -15, reason: 'Oil fund growth slows; energy revenue drops', reasonZh: '石油基金增长放缓；能源收入下降' },
        { countryId: 'USA', severity: 'medium', direction: 'mixed', impactPercent: 5, reason: 'Shale industry hurt but consumers benefit', reasonZh: '页岩产业受损但消费者受益' },
        { countryId: 'CHN', severity: 'medium', direction: 'positive', impactPercent: 15, reason: 'Cheap energy boosts manufacturing', reasonZh: '廉价能源提振制造业' },
        { countryId: 'IND', severity: 'medium', direction: 'positive', impactPercent: 18, reason: 'Major oil importer; costs plummet', reasonZh: '主要石油进口国；成本骤降' },
        { countryId: 'JPN', severity: 'medium', direction: 'positive', impactPercent: 12, reason: 'Energy import bill drops significantly', reasonZh: '能源进口账单大幅下降' },
      ],
      cityImpacts: [
        { cityId: 'riyadh', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'moscow', severity: 'critical', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'lagos', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'houston', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'mumbai', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'shanghai', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
      ],
      activatedRelationships: [
        'CHN-SAU-energy_dependency', 'CHN-RUS-energy_dependency', 'CHN-IRN-energy_dependency',
        'JPN-SAU-energy_dependency', 'IND-SAU-energy_dependency', 'IND-IRN-energy_dependency',
        'USA-SAU-energy_dependency', 'USA-SAU-political', 'SAU-IRN-political',
        'SAU-ARE-military_alliance',
      ],
      summary: 'An OPEC+ collapse would trigger an oil price war, potentially pushing crude below $30/barrel. Oil-dependent economies like Russia, Venezuela, and Nigeria would face fiscal crises, while major importers like China, India, and Japan would enjoy an economic boost from cheap energy.',
      summaryZh: 'OPEC+崩溃将引发石油价格战，可能推动原油价格跌破30美元/桶。俄罗斯、委内瑞拉和尼日利亚等石油依赖经济体将面临财政危机，而中国、印度和日本等主要进口国将从廉价能源中获得经济提振。',
    },
  },
  {
    id: 'european-energy-crisis',
    name: 'European Energy Crisis',
    nameCn: '欧洲能源危机',
    category: 'energy',
    description: 'Russia completely cuts gas supply to Europe during winter.',
    descriptionZh: '俄罗斯在冬季完全切断对欧洲的天然气供应。',
    eventText: 'What if Russia completely cuts all natural gas supply to Europe?',
    keywords: ['europe', 'energy', 'gas', 'russia', 'nord stream', 'winter', '欧洲', '能源', '天然气', '俄罗斯', '北溪'],
    result: {
      event: 'Russia completely cuts gas supply to Europe',
      timestamp: '2026-01-10T00:00:00Z',
      epicenter: { countryId: 'DEU', coordinates: [10.45, 51.17] },
      countryImpacts: [
        { countryId: 'DEU', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Largest consumer of Russian gas; industry paralyzed', reasonZh: '俄罗斯天然气最大消费国；工业瘫痪' },
        { countryId: 'ITA', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Heavily dependent on Russian gas', reasonZh: '严重依赖俄罗斯天然气' },
        { countryId: 'POL', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Transit country; industrial shortages', reasonZh: '过境国；工业短缺' },
        { countryId: 'FRA', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Nuclear cushion but gas still needed', reasonZh: '核能缓冲但仍需天然气' },
        { countryId: 'NLD', severity: 'medium', direction: 'negative', impactPercent: -14, reason: 'Gas-dependent economy; heating crisis', reasonZh: '天然气依赖经济；供暖危机' },
        { countryId: 'GBR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Energy price surge; industrial slowdown', reasonZh: '能源价格飙升；工业放缓' },
        { countryId: 'NOR', severity: 'medium', direction: 'positive', impactPercent: 20, reason: 'Alternative gas supplier; windfall profits', reasonZh: '替代天然气供应商；暴利' },
        { countryId: 'RUS', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Lost its largest gas customer revenue', reasonZh: '失去最大天然气客户收入' },
        { countryId: 'USA', severity: 'low', direction: 'positive', impactPercent: 8, reason: 'LNG exports to Europe surge', reasonZh: '对欧液化天然气出口激增' },
        { countryId: 'TUR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Energy costs spike; transit role complicated', reasonZh: '能源成本飙升；过境角色复杂化' },
      ],
      cityImpacts: [
        { cityId: 'berlin', severity: 'critical', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'frankfurt', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'amsterdam', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'rome', severity: 'high', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'oslo', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'moscow', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
      ],
      activatedRelationships: [
        'DEU-RUS-energy_dependency', 'ITA-RUS-energy_dependency', 'TUR-RUS-energy_dependency',
        'UKR-RUS-energy_dependency', 'POL-NOR-energy_dependency', 'FRA-NOR-energy_dependency',
        'NLD-NOR-energy_dependency', 'GBR-NOR-energy_dependency', 'DEU-FRA-trade',
        'DEU-NLD-trade',
      ],
      summary: 'A complete Russian gas cutoff to Europe would trigger an energy emergency affecting 150 million people, shutting down energy-intensive industries in Germany and Italy. Norway would become Europe\'s lifeline, while LNG imports from the US and Qatar would surge but take months to scale.',
      summaryZh: '俄罗斯完全切断对欧洲的天然气供应将引发影响1.5亿人的能源紧急状态，关闭德国和意大利的能源密集型工业。挪威将成为欧洲的生命线，而来自美国和卡塔尔的液化天然气进口将激增但需要数月才能扩大规模。',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // CLIMATE (4)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pacific-mega-typhoon',
    name: 'Pacific Mega-Typhoon',
    nameCn: '太平洋超级台风',
    category: 'climate',
    description: 'Category 5+ super typhoon devastates East Asian coastlines.',
    descriptionZh: '5级以上超级台风摧毁东亚海岸线。',
    eventText: 'What if a category 5+ super typhoon hits major East Asian cities?',
    keywords: ['typhoon', 'hurricane', 'pacific', 'storm', 'flood', '台风', '飓风', '太平洋', '风暴', '洪水'],
    result: {
      event: 'Category 5+ super typhoon devastates East Asian coastlines',
      timestamp: '2026-09-01T00:00:00Z',
      epicenter: { countryId: 'PHL', coordinates: [125.0, 13.0] },
      countryImpacts: [
        { countryId: 'PHL', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Direct landfall; infrastructure destroyed', reasonZh: '直接登陆；基础设施被摧毁' },
        { countryId: 'TWN', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'TSMC fabs at risk; coastal flooding', reasonZh: '台积电晶圆厂面临风险；沿海洪水' },
        { countryId: 'JPN', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Coastal cities and ports damaged', reasonZh: '沿海城市和港口受损' },
        { countryId: 'CHN', severity: 'medium', direction: 'negative', impactPercent: -15, reason: 'Southern coast manufacturing disrupted', reasonZh: '南方沿海制造业中断' },
        { countryId: 'VNM', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Coastal damage; agricultural loss', reasonZh: '沿海损害；农业损失' },
        { countryId: 'KOR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Port and shipping disruption', reasonZh: '港口和航运中断' },
        { countryId: 'SGP', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Shipping route delays', reasonZh: '航运路线延误' },
      ],
      cityImpacts: [
        { cityId: 'manila', severity: 'critical', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'taipei', severity: 'high', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'tokyo', severity: 'medium', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'guangzhou', severity: 'medium', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'hong-kong', severity: 'medium', direction: 'negative', impactType: 'infrastructure_damage' },
      ],
      activatedRelationships: [
        'CHN-VNM-geographic_proximity', 'JPN-TWN-supply_chain', 'USA-TWN-supply_chain',
        'CHN-TWN-supply_chain', 'JPN-SGP-trade', 'CHN-SGP-trade',
      ],
      summary: 'A category 5+ super typhoon striking East Asia could cause $200B+ in damage, potentially knocking TSMC semiconductor fabs offline and disrupting global chip supply. Philippines would face a humanitarian catastrophe while coastal megacities across the region would suffer flooding and infrastructure damage.',
      summaryZh: '5级以上超级台风袭击东亚可能造成超过2000亿美元的损失，可能使台积电半导体晶圆厂停工并扰乱全球芯片供应。菲律宾将面临人道主义灾难，而该地区的沿海大城市将遭受洪水和基础设施损害。',
    },
  },
  {
    id: 'arctic-shipping-route',
    name: 'Arctic Shipping Route Opens',
    nameCn: '北极航线开通',
    category: 'climate',
    description: 'Year-round Arctic shipping becomes viable due to ice melt.',
    descriptionZh: '由于冰层融化，全年北极航运成为可能。',
    eventText: 'What if Arctic ice melts enough to open year-round shipping routes?',
    keywords: ['arctic', 'ice', 'melt', 'shipping', 'northern passage', '北极', '冰', '融化', '航运', '北方航道'],
    result: {
      event: 'Year-round Arctic shipping routes open due to ice melt',
      timestamp: '2026-06-01T00:00:00Z',
      epicenter: { countryId: 'RUS', coordinates: [105.32, 75.0] },
      countryImpacts: [
        { countryId: 'RUS', severity: 'high', direction: 'positive', impactPercent: 25, reason: 'Controls Northern Sea Route; massive revenue opportunity', reasonZh: '控制北方海路；巨大收入机遇' },
        { countryId: 'NOR', severity: 'medium', direction: 'positive', impactPercent: 15, reason: 'Arctic infrastructure and resource access', reasonZh: '北极基础设施和资源开发' },
        { countryId: 'CAN', severity: 'medium', direction: 'positive', impactPercent: 12, reason: 'Northwest Passage becomes viable', reasonZh: '西北航道变得可行' },
        { countryId: 'CHN', severity: 'medium', direction: 'positive', impactPercent: 10, reason: 'Shorter shipping to Europe; Polar Silk Road', reasonZh: '到欧洲的航程更短；冰上丝绸之路' },
        { countryId: 'EGY', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Suez Canal traffic diverted to Arctic', reasonZh: '苏伊士运河交通转向北极' },
        { countryId: 'SGP', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Global shipping hub bypassed', reasonZh: '全球航运枢纽被绕过' },
        { countryId: 'SWE', severity: 'low', direction: 'positive', impactPercent: 8, reason: 'Arctic access; Nordic shipping boost', reasonZh: '北极通道；北欧航运提振' },
        { countryId: 'JPN', severity: 'low', direction: 'positive', impactPercent: 6, reason: 'Shorter Europe trade route', reasonZh: '更短的欧洲贸易路线' },
      ],
      cityImpacts: [
        { cityId: 'saint-petersburg', severity: 'high', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'suez', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'singapore', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'rotterdam', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'stockholm', severity: 'low', direction: 'positive', impactType: 'opportunity' },
      ],
      activatedRelationships: [
        'NOR-SWE-geographic_proximity', 'CHN-RUS-energy_dependency',
        'CHN-RUS-political', 'EGY-SAU-energy_dependency',
        'SGP-MYS-trade', 'SGP-IDN-trade',
      ],
      summary: 'Year-round Arctic shipping would cut Europe-Asia transit by 40%, fundamentally disrupting global maritime trade. Russia would gain control of the most strategic new waterway since the Panama Canal, while Egypt\'s Suez Canal and Singapore\'s shipping hub would lose significant traffic.',
      summaryZh: '全年北极航运将使欧亚运输时间缩短40%，从根本上颠覆全球海运贸易。俄罗斯将获得自巴拿马运河以来最具战略意义的新水道的控制权，而埃及的苏伊士运河和新加坡的航运枢纽将失去大量交通。',
    },
  },
  {
    id: 'sahel-drought-crisis',
    name: 'Sahel Drought & Migration Crisis',
    nameCn: '萨赫勒干旱与移民危机',
    category: 'climate',
    description: 'Severe multi-year drought triggers mass migration from the Sahel region.',
    descriptionZh: '严重的多年干旱引发萨赫勒地区的大规模移民。',
    eventText: 'What if a severe drought in the Sahel triggers a mass migration crisis?',
    keywords: ['sahel', 'drought', 'africa', 'migration', 'famine', 'climate', '萨赫勒', '干旱', '非洲', '移民', '饥荒', '气候'],
    result: {
      event: 'Severe Sahel drought triggers mass migration crisis',
      timestamp: '2026-07-01T00:00:00Z',
      epicenter: { countryId: 'NGA', coordinates: [8.68, 12.0] },
      countryImpacts: [
        { countryId: 'NGA', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Food crisis; internal displacement of millions', reasonZh: '粮食危机；数百万人国内流离失所' },
        { countryId: 'ETH', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Drought compounds existing instability', reasonZh: '干旱加剧现有不稳定' },
        { countryId: 'EGY', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Migration pressure from south; Nile water disputes', reasonZh: '来自南方的移民压力；尼罗河水争端' },
        { countryId: 'FRA', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Migration pressure from former colonies', reasonZh: '来自前殖民地的移民压力' },
        { countryId: 'ITA', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Mediterranean migration surge', reasonZh: '地中海移民激增' },
        { countryId: 'ESP', severity: 'medium', direction: 'negative', impactPercent: -6, reason: 'Migration route via Morocco', reasonZh: '经摩洛哥的移民路线' },
        { countryId: 'ZAF', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Regional instability; refugee flows', reasonZh: '区域不稳定；难民流动' },
      ],
      cityImpacts: [
        { cityId: 'lagos', severity: 'critical', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'abuja', severity: 'high', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'addis-ababa', severity: 'high', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'cairo', severity: 'medium', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'paris', severity: 'low', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'rome', severity: 'low', direction: 'negative', impactType: 'refugee_crisis' },
      ],
      activatedRelationships: [
        'ISR-EGY-political', 'ISR-EGY-geographic_proximity',
        'GBR-FRA-trade', 'DEU-FRA-trade', 'FRA-DEU-political',
        'EGY-SAU-geographic_proximity',
      ],
      summary: 'A severe Sahel drought would displace 20+ million people, creating the largest migration crisis in history. Food prices would spike across Africa, migration pressure on Europe would overwhelm border systems, and political instability could topple governments in Nigeria and Ethiopia.',
      summaryZh: '严重的萨赫勒干旱将导致2000多万人流离失所，造成历史上最大的移民危机。非洲各地粮食价格将飙升，对欧洲的移民压力将压垮边境系统，政治不稳定可能推翻尼日利亚和埃塞俄比亚的政府。',
    },
  },
  {
    id: 'amazon-wildfire-crisis',
    name: 'Amazon Wildfire Crisis',
    nameCn: '亚马逊野火危机',
    category: 'climate',
    description: 'Unprecedented wildfires destroy large portions of the Amazon rainforest.',
    descriptionZh: '前所未有的野火摧毁了亚马逊雨林的大片区域。',
    eventText: 'What if unprecedented wildfires destroy a major portion of the Amazon rainforest?',
    keywords: ['amazon', 'wildfire', 'rainforest', 'brazil', 'deforestation', '亚马逊', '野火', '雨林', '巴西', '森林砍伐'],
    result: {
      event: 'Unprecedented wildfires destroy Amazon rainforest',
      timestamp: '2026-08-01T00:00:00Z',
      epicenter: { countryId: 'BRA', coordinates: [-60.0, -3.0] },
      countryImpacts: [
        { countryId: 'BRA', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Ecological catastrophe; international sanctions threat', reasonZh: '生态灾难；国际制裁威胁' },
        { countryId: 'COL', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Amazon border fires; air quality crisis', reasonZh: '亚马逊边境火灾；空气质量危机' },
        { countryId: 'ARG', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Regional climate impact; trade partner affected', reasonZh: '区域气候影响；贸易伙伴受影响' },
        { countryId: 'USA', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Climate pressure; commodity market disruption', reasonZh: '气候压力；商品市场混乱' },
        { countryId: 'DEU', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'EU trade agreement suspended over deforestation', reasonZh: '欧盟因森林砍伐暂停贸易协定' },
        { countryId: 'CHN', severity: 'low', direction: 'negative', impactPercent: -6, reason: 'Soy and commodity supply disrupted', reasonZh: '大豆和商品供应中断' },
        { countryId: 'FRA', severity: 'low', direction: 'negative', impactPercent: -4, reason: 'French Guiana proximity; EU sanctions push', reasonZh: '法属圭亚那邻近；欧盟制裁推动' },
      ],
      cityImpacts: [
        { cityId: 'sao-paulo', severity: 'high', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'rio-de-janeiro', severity: 'medium', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'bogota', severity: 'medium', direction: 'negative', impactType: 'other' },
        { cityId: 'buenos-aires', severity: 'low', direction: 'negative', impactType: 'trade_disruption' },
      ],
      activatedRelationships: [
        'CHN-BRA-trade', 'BRA-ARG-trade', 'DEU-FRA-trade',
        'GBR-FRA-trade', 'USA-CHN-trade',
      ],
      summary: 'Unprecedented Amazon wildfires would release billions of tons of CO2, accelerate global warming, and trigger international sanctions on Brazil. Global commodity markets for soy, beef, and timber would spike, while South American neighbors would face cross-border air pollution and climate disruption.',
      summaryZh: '前所未有的亚马逊野火将释放数十亿吨二氧化碳，加速全球变暖，并引发对巴西的国际制裁。大豆、牛肉和木材的全球商品市场将飙升，南美邻国将面临跨境空气污染和气候混乱。',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // HEALTH (2)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'global-pandemic-outbreak',
    name: 'New Global Pandemic Outbreak',
    nameCn: '新全球疫情爆发',
    category: 'health',
    description: 'A novel pathogen emerges with high transmissibility and mortality.',
    descriptionZh: '一种高传播性和高致死率的新型病原体出现。',
    eventText: 'What if a new highly contagious and deadly pandemic emerges?',
    keywords: ['pandemic', 'virus', 'outbreak', 'covid', 'disease', 'quarantine', '疫情', '病毒', '爆发', '新冠', '疾病', '隔离'],
    result: {
      event: 'New highly contagious pandemic emerges globally',
      timestamp: '2026-03-01T00:00:00Z',
      epicenter: { countryId: 'CHN', coordinates: [114.0, 30.5] },
      countryImpacts: [
        { countryId: 'CHN', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Origin point; manufacturing shutdown', reasonZh: '起源地；制造业停工' },
        { countryId: 'USA', severity: 'critical', direction: 'negative', impactPercent: -25, reason: 'Healthcare system overwhelmed; GDP crash', reasonZh: '医疗系统不堪重负；GDP暴跌' },
        { countryId: 'IND', severity: 'critical', direction: 'negative', impactPercent: -28, reason: 'Dense population; healthcare infrastructure stressed', reasonZh: '人口密集；医疗基础设施紧张' },
        { countryId: 'BRA', severity: 'high', direction: 'negative', impactPercent: -22, reason: 'Large population vulnerable; economic hit', reasonZh: '大量人口脆弱；经济受创' },
        { countryId: 'GBR', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Travel hub; financial center disrupted', reasonZh: '交通枢纽；金融中心中断' },
        { countryId: 'DEU', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Industrial output drops; supply chain breaks', reasonZh: '工业产出下降；供应链断裂' },
        { countryId: 'JPN', severity: 'medium', direction: 'negative', impactPercent: -15, reason: 'Aging population at high risk', reasonZh: '老龄化人口面临高风险' },
        { countryId: 'IDN', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Island geography complicates containment', reasonZh: '岛屿地理使遏制复杂化' },
        { countryId: 'NGA', severity: 'medium', direction: 'negative', impactPercent: -18, reason: 'Weak healthcare system; rapid spread', reasonZh: '薄弱的医疗系统；快速传播' },
        { countryId: 'SGP', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Travel hub; trade disrupted', reasonZh: '交通枢纽；贸易中断' },
      ],
      cityImpacts: [
        { cityId: 'shanghai', severity: 'critical', direction: 'negative', impactType: 'other' },
        { cityId: 'new-york', severity: 'critical', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'london', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'mumbai', severity: 'high', direction: 'negative', impactType: 'other' },
        { cityId: 'tokyo', severity: 'high', direction: 'negative', impactType: 'other' },
        { cityId: 'singapore', severity: 'medium', direction: 'negative', impactType: 'trade_disruption' },
      ],
      activatedRelationships: [
        'USA-CHN-trade', 'USA-CHN-supply_chain', 'CHN-JPN-trade',
        'USA-GBR-trade', 'USA-DEU-trade', 'CHN-SGP-trade',
        'IND-BGD-geographic_proximity', 'SGP-IDN-trade',
      ],
      summary: 'A new global pandemic would dwarf COVID-19\'s economic impact, potentially causing $20T+ in global GDP losses. International travel would halt, global supply chains would collapse, and countries with weak healthcare systems would face catastrophic mortality rates.',
      summaryZh: '新的全球疫情将使新冠肺炎的经济影响相形见绌，可能造成超过20万亿美元的全球GDP损失。国际旅行将中断，全球供应链将崩溃，医疗系统薄弱的国家将面临灾难性的死亡率。',
    },
  },
  {
    id: 'avian-flu-pandemic',
    name: 'Avian Flu Pandemic',
    nameCn: '禽流感大流行',
    category: 'health',
    description: 'H5N1 avian flu mutates for human-to-human transmission.',
    descriptionZh: 'H5N1禽流感变异为人传人传播。',
    eventText: 'What if avian flu mutates for efficient human-to-human transmission?',
    keywords: ['avian flu', 'bird flu', 'h5n1', 'mutation', 'poultry', '禽流感', '鸟流感', '变异', '家禽'],
    result: {
      event: 'H5N1 avian flu mutates for human-to-human transmission',
      timestamp: '2026-04-01T00:00:00Z',
      epicenter: { countryId: 'THA', coordinates: [100.99, 15.87] },
      countryImpacts: [
        { countryId: 'THA', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Outbreak origin; poultry industry devastated', reasonZh: '爆发起源地；家禽业被摧毁' },
        { countryId: 'VNM', severity: 'high', direction: 'negative', impactPercent: -22, reason: 'Major poultry producer; cross-border spread', reasonZh: '主要家禽生产国；跨境传播' },
        { countryId: 'CHN', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Largest poultry market; containment challenge', reasonZh: '最大家禽市场；遏制挑战' },
        { countryId: 'IDN', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Endemic H5N1 in poultry flocks', reasonZh: 'H5N1在家禽中流行' },
        { countryId: 'IND', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Dense population; limited healthcare access', reasonZh: '人口密集；医疗资源有限' },
        { countryId: 'BRA', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Major poultry exporter; trade bans', reasonZh: '主要家禽出口国；贸易禁令' },
        { countryId: 'USA', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Agricultural sector hit; vaccine race', reasonZh: '农业部门受创；疫苗竞赛' },
        { countryId: 'JPN', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Food security concerns; import bans', reasonZh: '粮食安全担忧；进口禁令' },
      ],
      cityImpacts: [
        { cityId: 'bangkok', severity: 'critical', direction: 'negative', impactType: 'other' },
        { cityId: 'ho-chi-minh', severity: 'high', direction: 'negative', impactType: 'other' },
        { cityId: 'jakarta', severity: 'high', direction: 'negative', impactType: 'other' },
        { cityId: 'beijing', severity: 'medium', direction: 'negative', impactType: 'other' },
        { cityId: 'sao-paulo', severity: 'medium', direction: 'negative', impactType: 'trade_disruption' },
      ],
      activatedRelationships: [
        'THA-MYS-geographic_proximity', 'CHN-VNM-geographic_proximity',
        'CHN-THA-supply_chain', 'JPN-THA-supply_chain',
        'IDN-MYS-geographic_proximity', 'IND-BGD-supply_chain',
      ],
      summary: 'An H5N1 mutation enabling human-to-human transmission would be a worst-case pandemic scenario with 50%+ mortality rates in early waves. The global poultry industry ($300B) would face mass culling, food prices would spike, and Southeast Asian economies dependent on agriculture and tourism would be devastated.',
      summaryZh: 'H5N1变异实现人传人传播将是最坏的疫情场景，早期浪潮的死亡率超过50%。全球家禽业（3000亿美元）将面临大规模扑杀，粮食价格将飙升，依赖农业和旅游业的东南亚经济体将遭受重创。',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // POLITICAL (5)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'ukraine-russia-escalation',
    name: 'Ukraine-Russia Conflict Escalation',
    nameCn: '乌克兰-俄罗斯冲突升级',
    category: 'political',
    description: 'Russia dramatically escalates its war in Ukraine with massive offensive.',
    descriptionZh: '俄罗斯大规模进攻急剧升级乌克兰战争。',
    eventText: 'What if Russia dramatically escalates its offensive in Ukraine?',
    keywords: ['ukraine', 'russia', 'war', 'offensive', 'escalation', '乌克兰', '俄罗斯', '战争', '进攻', '升级'],
    result: {
      event: 'Russia dramatically escalates offensive in Ukraine',
      timestamp: '2026-02-24T00:00:00Z',
      epicenter: { countryId: 'UKR', coordinates: [31.17, 48.38] },
      countryImpacts: [
        { countryId: 'UKR', severity: 'critical', direction: 'negative', impactPercent: -50, reason: 'Massive military escalation; existential threat', reasonZh: '大规模军事升级；生存威胁' },
        { countryId: 'RUS', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Sanctions deepen; military overextension', reasonZh: '制裁加深；军事过度扩张' },
        { countryId: 'POL', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Front-line NATO state; refugee surge', reasonZh: '北约前线国家；难民激增' },
        { countryId: 'DEU', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Defense spending surge; energy costs', reasonZh: '国防支出激增；能源成本' },
        { countryId: 'GBR', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Increased military support costs', reasonZh: '军事支持成本增加' },
        { countryId: 'FRA', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'EU security burden; military aid', reasonZh: '欧盟安全负担；军事援助' },
        { countryId: 'USA', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Military aid surge; geopolitical tension', reasonZh: '军事援助激增；地缘政治紧张' },
        { countryId: 'CHN', severity: 'low', direction: 'mixed', impactPercent: -3, reason: 'Diplomatic balancing act strained', reasonZh: '外交平衡术受到考验' },
        { countryId: 'TUR', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Black Sea security; grain export disruption', reasonZh: '黑海安全；粮食出口中断' },
      ],
      cityImpacts: [
        { cityId: 'kyiv', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'odesa', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'moscow', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'warsaw', severity: 'medium', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'berlin', severity: 'medium', direction: 'negative', impactType: 'energy_crisis' },
      ],
      activatedRelationships: [
        'RUS-UKR-political', 'RUS-UKR-geographic_proximity', 'UKR-RUS-energy_dependency',
        'DEU-RUS-energy_dependency', 'USA-POL-military_alliance', 'USA-GBR-military_alliance',
        'USA-DEU-military_alliance', 'CHN-RUS-political', 'TUR-RUS-energy_dependency',
        'DEU-POL-geographic_proximity',
      ],
      summary: 'A dramatic Russian escalation in Ukraine would push Europe to full war footing, trigger massive new sanctions, disrupt global grain supplies (Ukraine exports 10% of world wheat), and raise the specter of nuclear conflict for the first time since the Cold War.',
      summaryZh: '俄罗斯在乌克兰的急剧升级将推动欧洲进入全面战争状态，触发大规模新制裁，扰乱全球粮食供应（乌克兰出口全球10%的小麦），并自冷战以来首次提出核冲突的可能性。',
    },
  },
  {
    id: 'iran-nuclear-crisis',
    name: 'Iran Nuclear Weapons Crisis',
    nameCn: '伊朗核武器危机',
    category: 'political',
    description: 'Iran announces successful development of nuclear weapons.',
    descriptionZh: '伊朗宣布成功研发核武器。',
    eventText: 'What if Iran successfully develops nuclear weapons?',
    keywords: ['iran', 'nuclear', 'weapon', 'uranium', 'enrichment', '伊朗', '核', '武器', '铀', '浓缩'],
    result: {
      event: 'Iran announces successful nuclear weapons development',
      timestamp: '2026-05-01T00:00:00Z',
      epicenter: { countryId: 'IRN', coordinates: [53.69, 32.43] },
      countryImpacts: [
        { countryId: 'IRN', severity: 'high', direction: 'mixed', impactPercent: -15, reason: 'Severe sanctions but strategic deterrence gained', reasonZh: '严厉制裁但获得战略威慑' },
        { countryId: 'ISR', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Existential threat; military strike consideration', reasonZh: '生存威胁；考虑军事打击' },
        { countryId: 'SAU', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Regional rival now nuclear-armed; arms race', reasonZh: '区域对手拥核；军备竞赛' },
        { countryId: 'IRQ', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Iranian influence grows with nuclear backing', reasonZh: '核力量支撑下伊朗影响力增长' },
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -12, reason: 'Non-proliferation failure; Middle East instability', reasonZh: '防扩散失败；中东不稳定' },
        { countryId: 'ARE', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Regional security environment deteriorates', reasonZh: '区域安全环境恶化' },
        { countryId: 'TUR', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Nuclear neighbor; proliferation pressure', reasonZh: '核邻国；扩散压力' },
        { countryId: 'EGY', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Regional power balance shifted', reasonZh: '区域力量平衡转变' },
        { countryId: 'RUS', severity: 'low', direction: 'mixed', impactPercent: -3, reason: 'Complicated ally relationship', reasonZh: '复杂的盟友关系' },
        { countryId: 'PAK', severity: 'low', direction: 'mixed', impactPercent: -4, reason: 'Nuclear neighbor; Sunni-Shia dynamics', reasonZh: '核邻国；逊尼派-什叶派动态' },
      ],
      cityImpacts: [
        { cityId: 'tehran', severity: 'high', direction: 'mixed', impactType: 'military_threat' },
        { cityId: 'tel-aviv', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'jerusalem', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'riyadh', severity: 'high', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'dubai', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'baghdad', severity: 'medium', direction: 'negative', impactType: 'military_threat' },
      ],
      activatedRelationships: [
        'ISR-IRN-political', 'SAU-IRN-political', 'RUS-IRN-military_alliance',
        'IRN-IRQ-political', 'IRN-IRQ-geographic_proximity', 'USA-ISR-political',
        'USA-ISR-military_alliance', 'USA-SAU-political', 'SAU-ARE-military_alliance',
        'PAK-IRN-geographic_proximity',
      ],
      summary: 'Iran achieving nuclear weapons capability would shatter the non-proliferation regime, trigger a Middle East nuclear arms race (Saudi Arabia, Turkey, Egypt would seek their own), and bring Israel to the brink of a preemptive military strike — the most destabilizing event in the region since the 1979 revolution.',
      summaryZh: '伊朗获得核武器能力将打破核不扩散体制，引发中东核军备竞赛（沙特阿拉伯、土耳其、埃及将寻求自己的核武器），并将以色列推向先发制人军事打击的边缘——这是自1979年革命以来该地区最具破坏性的事件。',
    },
  },
  {
    id: 'middle-east-regional-war',
    name: 'Middle East Regional War',
    nameCn: '中东区域战争',
    category: 'political',
    description: 'Multi-front regional war erupts across the Middle East.',
    descriptionZh: '中东爆发多条战线的区域战争。',
    eventText: 'What if a multi-front regional war erupts in the Middle East?',
    keywords: ['middle east', 'war', 'regional', 'israel', 'iran', 'conflict', '中东', '战争', '区域', '以色列', '冲突'],
    result: {
      event: 'Multi-front regional war erupts in the Middle East',
      timestamp: '2026-06-01T00:00:00Z',
      epicenter: { countryId: 'ISR', coordinates: [34.85, 31.05] },
      countryImpacts: [
        { countryId: 'ISR', severity: 'critical', direction: 'negative', impactPercent: -40, reason: 'Multi-front war; existential defense mode', reasonZh: '多条战线战争；生存防御模式' },
        { countryId: 'IRN', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Direct participant; international isolation', reasonZh: '直接参与方；国际孤立' },
        { countryId: 'IRQ', severity: 'high', direction: 'negative', impactPercent: -25, reason: 'Proxy conflict theater; oil exports disrupted', reasonZh: '代理冲突战区；石油出口中断' },
        { countryId: 'SAU', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Oil infrastructure threatened; defense mobilization', reasonZh: '石油基础设施受威胁；国防动员' },
        { countryId: 'EGY', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Border security; Sinai concerns', reasonZh: '边境安全；西奈半岛担忧' },
        { countryId: 'TUR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Regional power drawn in; refugee crisis', reasonZh: '区域大国被卷入；难民危机' },
        { countryId: 'ARE', severity: 'medium', direction: 'negative', impactPercent: -15, reason: 'Oil infrastructure targeted; trade disrupted', reasonZh: '石油基础设施被攻击；贸易中断' },
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Major ally at war; oil price shock', reasonZh: '主要盟友陷入战争；石油价格冲击' },
        { countryId: 'CHN', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Oil supply disruption from Gulf', reasonZh: '海湾石油供应中断' },
        { countryId: 'IND', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Energy costs spike; diaspora at risk', reasonZh: '能源成本飙升；侨民面临风险' },
      ],
      cityImpacts: [
        { cityId: 'tel-aviv', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'tehran', severity: 'critical', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'baghdad', severity: 'high', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'riyadh', severity: 'high', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'dubai', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'cairo', severity: 'medium', direction: 'negative', impactType: 'military_threat' },
        { cityId: 'istanbul', severity: 'medium', direction: 'negative', impactType: 'refugee_crisis' },
      ],
      activatedRelationships: [
        'ISR-IRN-political', 'SAU-IRN-political', 'USA-ISR-political',
        'USA-ISR-military_alliance', 'IRN-IRQ-political', 'IRN-IRQ-geographic_proximity',
        'ISR-EGY-political', 'ISR-EGY-geographic_proximity', 'TUR-IRQ-geographic_proximity',
        'SAU-IRQ-geographic_proximity', 'CHN-SAU-energy_dependency', 'IND-IRQ-energy_dependency',
      ],
      summary: 'A multi-front Middle East war would send oil prices above $250/barrel, threatening 30% of global petroleum supply. Israel would face simultaneous threats from multiple directions, while global energy markets would experience the worst crisis since the 1973 oil embargo.',
      summaryZh: '中东多条战线战争将推动油价超过250美元/桶，威胁全球30%的石油供应。以色列将面临来自多个方向的同时威胁，而全球能源市场将经历自1973年石油禁运以来最严重的危机。',
    },
  },
  {
    id: 'venezuela-state-collapse',
    name: 'Venezuela State Collapse',
    nameCn: '委内瑞拉国家崩溃',
    category: 'political',
    description: 'Venezuela experiences complete state failure and humanitarian catastrophe.',
    descriptionZh: '委内瑞拉经历完全的国家崩溃和人道主义灾难。',
    eventText: 'What if Venezuela experiences a complete state collapse?',
    keywords: ['venezuela', 'collapse', 'crisis', 'maduro', 'humanitarian', '委内瑞拉', '崩溃', '危机', '马杜罗', '人道主义'],
    result: {
      event: 'Venezuela complete state collapse',
      timestamp: '2026-07-01T00:00:00Z',
      epicenter: { countryId: 'VEN', coordinates: [-66.59, 6.42] },
      countryImpacts: [
        { countryId: 'VEN', severity: 'critical', direction: 'negative', impactPercent: -50, reason: 'Total institutional failure; humanitarian catastrophe', reasonZh: '制度完全失败；人道主义灾难' },
        { countryId: 'COL', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Massive refugee influx; border security crisis', reasonZh: '大规模难民涌入；边境安全危机' },
        { countryId: 'BRA', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Northern border refugee pressure', reasonZh: '北部边境难民压力' },
        { countryId: 'USA', severity: 'medium', direction: 'negative', impactPercent: -6, reason: 'Regional instability; migration wave; oil market impact', reasonZh: '区域不稳定；移民潮；石油市场影响' },
        { countryId: 'CHL', severity: 'low', direction: 'negative', impactPercent: -4, reason: 'Refugee destination; social pressure', reasonZh: '难民目的地；社会压力' },
        { countryId: 'ARG', severity: 'low', direction: 'negative', impactPercent: -4, reason: 'Regional instability; commodity markets', reasonZh: '区域不稳定；商品市场' },
        { countryId: 'CHN', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Billions in Venezuelan debt at risk', reasonZh: '数十亿美元委内瑞拉债务面临风险' },
      ],
      cityImpacts: [
        { cityId: 'bogota', severity: 'high', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'sao-paulo', severity: 'medium', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'houston', severity: 'medium', direction: 'negative', impactType: 'energy_crisis' },
        { cityId: 'santiago', severity: 'low', direction: 'negative', impactType: 'refugee_crisis' },
      ],
      activatedRelationships: [
        'BRA-ARG-trade', 'CHN-BRA-trade', 'USA-CHN-political',
        'USA-CAN-trade', 'USA-MEX-trade',
      ],
      summary: 'A complete Venezuelan state collapse would trigger the largest humanitarian crisis in Western Hemisphere history, with 10+ million refugees fleeing to Colombia, Brazil, and beyond. The loss of Venezuelan oil production (once 3M barrels/day) would tighten global markets.',
      summaryZh: '委内瑞拉的完全国家崩溃将引发西半球历史上最大的人道主义危机，超过1000万难民逃往哥伦比亚、巴西及其他地区。委内瑞拉石油产量（曾经每天300万桶）的损失将收紧全球市场。',
    },
  },
  {
    id: 'myanmar-civil-war-escalation',
    name: 'Myanmar Civil War Escalation',
    nameCn: '缅甸内战升级',
    category: 'political',
    description: 'Myanmar civil war escalates with regional spillover effects.',
    descriptionZh: '缅甸内战升级，产生区域溢出效应。',
    eventText: 'What if the Myanmar civil war escalates dramatically with regional spillover?',
    keywords: ['myanmar', 'burma', 'civil war', 'junta', 'coup', '缅甸', '内战', '军政府', '政变'],
    result: {
      event: 'Myanmar civil war escalates with regional spillover',
      timestamp: '2026-08-01T00:00:00Z',
      epicenter: { countryId: 'THA', coordinates: [98.5, 19.0] },
      countryImpacts: [
        { countryId: 'THA', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Border refugee crisis; cross-border conflict', reasonZh: '边境难民危机；跨境冲突' },
        { countryId: 'IND', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Northeast border instability; refugee influx', reasonZh: '东北边境不稳定；难民涌入' },
        { countryId: 'CHN', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Border security; pipeline investments threatened', reasonZh: '边境安全；管道投资受威胁' },
        { countryId: 'BGD', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Rohingya crisis deepens; more refugees', reasonZh: '罗兴亚危机加深；更多难民' },
        { countryId: 'SGP', severity: 'low', direction: 'negative', impactPercent: -4, reason: 'ASEAN credibility crisis; investment uncertainty', reasonZh: '东盟信誉危机；投资不确定性' },
        { countryId: 'MYS', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Refugee boat arrivals; ASEAN tensions', reasonZh: '难民船到达；东盟紧张' },
        { countryId: 'JPN', severity: 'low', direction: 'negative', impactPercent: -3, reason: 'Development investments at risk', reasonZh: '发展投资面临风险' },
      ],
      cityImpacts: [
        { cityId: 'bangkok', severity: 'high', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'dhaka', severity: 'medium', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'kuala-lumpur', severity: 'low', direction: 'negative', impactType: 'refugee_crisis' },
        { cityId: 'singapore', severity: 'low', direction: 'negative', impactType: 'other' },
      ],
      activatedRelationships: [
        'THA-MYS-geographic_proximity', 'IND-BGD-geographic_proximity',
        'CHN-VNM-geographic_proximity', 'SGP-MYS-geographic_proximity',
        'IDN-MYS-geographic_proximity', 'IND-BGD-supply_chain',
      ],
      summary: 'A dramatic escalation of Myanmar\'s civil war would flood Thailand and Bangladesh with refugees, threaten Chinese pipeline investments worth $2B, destabilize ASEAN unity, and create a power vacuum exploited by drug cartels and armed militias across the Golden Triangle.',
      summaryZh: '缅甸内战的急剧升级将使泰国和孟加拉国涌入大量难民，威胁价值20亿美元的中国管道投资，破坏东盟团结，并在金三角地区创造被毒品卡特尔和武装民兵利用的权力真空。',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // ECONOMIC (2)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'global-debt-crisis',
    name: 'Global Sovereign Debt Crisis',
    nameCn: '全球主权债务危机',
    category: 'economic',
    description: 'Multiple major economies face simultaneous sovereign debt defaults.',
    descriptionZh: '多个主要经济体同时面临主权债务违约。',
    eventText: 'What if multiple major economies default on their sovereign debt simultaneously?',
    keywords: ['debt', 'default', 'sovereign', 'crisis', 'bond', 'fiscal', '债务', '违约', '主权', '危机', '债券', '财政'],
    result: {
      event: 'Multiple major economies default on sovereign debt',
      timestamp: '2026-09-01T00:00:00Z',
      epicenter: { countryId: 'USA', coordinates: [-77.04, 38.90] },
      countryImpacts: [
        { countryId: 'USA', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Treasury market crisis; dollar confidence shaken', reasonZh: '国债市场危机；美元信心动摇' },
        { countryId: 'JPN', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Highest debt-to-GDP ratio; yen collapse', reasonZh: '最高债务占GDP比率；日元崩溃' },
        { countryId: 'ITA', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Eurozone contagion trigger', reasonZh: '欧元区蔓延触发点' },
        { countryId: 'GBR', severity: 'high', direction: 'negative', impactPercent: -22, reason: 'Gilt market crisis; pound devaluation', reasonZh: '国债市场危机；英镑贬值' },
        { countryId: 'FRA', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Eurozone spillover; bank exposure', reasonZh: '欧元区溢出；银行风险敞口' },
        { countryId: 'DEU', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'EU bailout obligations; export decline', reasonZh: '欧盟救助义务；出口下降' },
        { countryId: 'CHN', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Largest US debt holder; export markets collapse', reasonZh: '最大美债持有者；出口市场崩溃' },
        { countryId: 'BRA', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Capital flight; currency crisis', reasonZh: '资本外逃；货币危机' },
        { countryId: 'IND', severity: 'medium', direction: 'negative', impactPercent: -15, reason: 'Foreign investment dries up; rupee weakens', reasonZh: '外资枯竭；卢比走弱' },
        { countryId: 'CHE', severity: 'medium', direction: 'positive', impactPercent: 10, reason: 'Safe haven currency; gold inflows', reasonZh: '避风港货币；黄金流入' },
      ],
      cityImpacts: [
        { cityId: 'new-york', severity: 'critical', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'london', severity: 'critical', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'tokyo', severity: 'critical', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'frankfurt', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'zurich', severity: 'medium', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'hong-kong', severity: 'high', direction: 'negative', impactType: 'market_crash' },
      ],
      activatedRelationships: [
        'USA-GBR-trade', 'USA-JPN-trade', 'USA-DEU-trade',
        'DEU-FRA-trade', 'DEU-ITA-trade', 'DEU-NLD-trade',
        'DEU-CHE-trade', 'GBR-FRA-trade', 'USA-CHN-trade',
        'CHN-JPN-trade',
      ],
      summary: 'A simultaneous sovereign debt crisis across major economies would trigger the worst financial meltdown in history, dwarfing the 2008 crisis. Bond markets would seize, currencies would crash, and the global financial system built on US Treasury "risk-free" assets would face existential questioning.',
      summaryZh: '主要经济体同时发生主权债务危机将触发历史上最严重的金融崩溃，使2008年危机相形见绌。债券市场将冻结，货币将暴跌，建立在美国国债"无风险"资产上的全球金融体系将面临根本性质疑。',
    },
  },
  {
    id: 'china-property-crash',
    name: 'China Property Market Collapse',
    nameCn: '中国房地产市场崩溃',
    category: 'economic',
    description: 'China\'s property sector crashes, triggering a banking and economic crisis.',
    descriptionZh: '中国房地产行业崩溃，引发银行业和经济危机。',
    eventText: 'What if China\'s property market completely collapses?',
    keywords: ['china', 'property', 'real estate', 'evergrande', 'housing', 'crash', '中国', '房地产', '恒大', '住房', '崩盘'],
    result: {
      event: 'China property market complete collapse',
      timestamp: '2026-10-01T00:00:00Z',
      epicenter: { countryId: 'CHN', coordinates: [113.26, 23.13] },
      countryImpacts: [
        { countryId: 'CHN', severity: 'critical', direction: 'negative', impactPercent: -35, reason: 'Property is 30% of GDP; banking crisis', reasonZh: '房地产占GDP的30%；银行危机' },
        { countryId: 'AUS', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Iron ore and commodity demand collapses', reasonZh: '铁矿石和商品需求崩溃' },
        { countryId: 'BRA', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Commodity export partner demand drops', reasonZh: '商品出口伙伴需求下降' },
        { countryId: 'KOR', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Trade exposure; construction equipment exports', reasonZh: '贸易风险敞口；建筑设备出口' },
        { countryId: 'JPN', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Trade partner slowdown; financial contagion', reasonZh: '贸易伙伴放缓；金融传染' },
        { countryId: 'DEU', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Industrial machinery exports to China decline', reasonZh: '对华工业机械出口下降' },
        { countryId: 'SGP', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Financial exposure; trade volumes drop', reasonZh: '金融风险敞口；贸易量下降' },
        { countryId: 'IDN', severity: 'low', direction: 'negative', impactPercent: -6, reason: 'Commodity exports to China decline', reasonZh: '对华商品出口下降' },
        { countryId: 'VNM', severity: 'low', direction: 'positive', impactPercent: 5, reason: 'Manufacturing shift from China accelerates', reasonZh: '从中国转移的制造业加速' },
      ],
      cityImpacts: [
        { cityId: 'guangzhou', severity: 'critical', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'shenzhen', severity: 'critical', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'shanghai', severity: 'critical', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'hong-kong', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'sydney', severity: 'high', direction: 'negative', impactType: 'trade_disruption' },
        { cityId: 'seoul', severity: 'medium', direction: 'negative', impactType: 'trade_disruption' },
      ],
      activatedRelationships: [
        'CHN-AUS-trade', 'CHN-AUS-energy_dependency', 'CHN-BRA-trade',
        'CHN-JPN-trade', 'CHN-KOR-trade', 'CHN-SGP-trade',
        'CHN-VNM-trade', 'CHN-IDN-supply_chain', 'DEU-CHN-supply_chain',
      ],
      summary: 'A complete Chinese property market collapse would wipe out $60T in household wealth (property is 70% of Chinese family assets), trigger a banking crisis, and send shockwaves through commodity markets. Australia, Brazil, and resource exporters would face severe recession.',
      summaryZh: '中国房地产市场的完全崩溃将消灭60万亿美元的家庭财富（房产占中国家庭资产的70%），引发银行危机，并冲击商品市场。澳大利亚、巴西和资源出口国将面临严重衰退。',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // TECHNOLOGY (4)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'semiconductor-disruption',
    name: 'Global Semiconductor Disruption',
    nameCn: '全球半导体供应中断',
    category: 'technology',
    description: 'TSMC production halted, causing global chip shortage emergency.',
    descriptionZh: '台积电生产中断，导致全球芯片短缺紧急状态。',
    eventText: 'What if TSMC production is completely halted?',
    keywords: ['semiconductor', 'chip', 'tsmc', 'shortage', 'fabrication', '半导体', '芯片', '台积电', '短缺', '制造'],
    result: {
      event: 'TSMC production completely halted',
      timestamp: '2026-03-01T00:00:00Z',
      epicenter: { countryId: 'TWN', coordinates: [120.96, 23.70] },
      countryImpacts: [
        { countryId: 'TWN', severity: 'critical', direction: 'negative', impactPercent: -40, reason: 'TSMC is 15% of GDP; economic cornerstone lost', reasonZh: '台积电占GDP的15%；经济基石丧失' },
        { countryId: 'USA', severity: 'critical', direction: 'negative', impactPercent: -25, reason: 'Apple, Nvidia, AMD depend on TSMC for chips', reasonZh: '苹果、英伟达、AMD依赖台积电的芯片' },
        { countryId: 'CHN', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Tech industry halted without advanced chips', reasonZh: '没有先进芯片科技产业停滞' },
        { countryId: 'JPN', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Auto and electronics industries starved of chips', reasonZh: '汽车和电子产业芯片匮乏' },
        { countryId: 'KOR', severity: 'high', direction: 'positive', impactPercent: 15, reason: 'Samsung gains market share; prices surge', reasonZh: '三星获得市场份额；价格飙升' },
        { countryId: 'DEU', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Auto industry production halted', reasonZh: '汽车工业生产停滞' },
        { countryId: 'IND', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Electronics and IT sector disrupted', reasonZh: '电子和IT部门中断' },
        { countryId: 'GBR', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Tech sector supply chain broken', reasonZh: '科技部门供应链断裂' },
        { countryId: 'SGP', severity: 'medium', direction: 'mixed', impactPercent: 5, reason: 'Alternative fab capacity gains value', reasonZh: '替代晶圆厂产能获得价值' },
      ],
      cityImpacts: [
        { cityId: 'taipei', severity: 'critical', direction: 'negative', impactType: 'supply_shortage' },
        { cityId: 'san-francisco', severity: 'critical', direction: 'negative', impactType: 'supply_shortage' },
        { cityId: 'seoul', severity: 'high', direction: 'positive', impactType: 'opportunity' },
        { cityId: 'tokyo', severity: 'high', direction: 'negative', impactType: 'supply_shortage' },
        { cityId: 'shenzhen', severity: 'high', direction: 'negative', impactType: 'supply_shortage' },
        { cityId: 'frankfurt', severity: 'medium', direction: 'negative', impactType: 'supply_shortage' },
      ],
      activatedRelationships: [
        'USA-TWN-supply_chain', 'CHN-TWN-supply_chain', 'JPN-TWN-supply_chain',
        'KOR-TWN-supply_chain', 'USA-KOR-trade', 'CHN-MYS-supply_chain',
        'USA-JPN-trade', 'DEU-CHN-supply_chain',
      ],
      summary: 'A complete TSMC shutdown would cut off 60% of global semiconductor production and 90% of advanced chips. Every smartphone, car, data center, and military system would face supply shortages. The global economic impact could exceed $1T within months.',
      summaryZh: '台积电完全停产将切断全球60%的半导体生产和90%的先进芯片。每一部智能手机、汽车、数据中心和军事系统都将面临供应短缺。全球经济影响可能在数月内超过1万亿美元。',
    },
  },
  {
    id: 'ai-arms-race',
    name: 'AI Military Arms Race',
    nameCn: 'AI军事军备竞赛',
    category: 'technology',
    description: 'Major powers enter an uncontrolled AI weapons development race.',
    descriptionZh: '大国进入失控的AI武器研发竞赛。',
    eventText: 'What if major powers enter an uncontrolled AI weapons arms race?',
    keywords: ['ai', 'artificial intelligence', 'weapons', 'arms race', 'autonomous', 'AI', '人工智能', '武器', '军备竞赛', '自主'],
    result: {
      event: 'Uncontrolled AI weapons arms race between major powers',
      timestamp: '2026-06-01T00:00:00Z',
      epicenter: { countryId: 'USA', coordinates: [-77.04, 38.90] },
      countryImpacts: [
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Massive defense spending; AI safety concerns', reasonZh: '大规模国防支出；AI安全担忧' },
        { countryId: 'CHN', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Military AI investment; international tensions', reasonZh: '军事AI投资；国际紧张' },
        { countryId: 'RUS', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Playing catch-up; defense budget strain', reasonZh: '追赶中；国防预算紧张' },
        { countryId: 'GBR', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Five Eyes AI integration; ethical debates', reasonZh: '五眼联盟AI整合；伦理争论' },
        { countryId: 'ISR', severity: 'medium', direction: 'mixed', impactPercent: -5, reason: 'AI defense leader but ethical scrutiny', reasonZh: 'AI防御领导者但面临伦理审查' },
        { countryId: 'JPN', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Constitutional constraints vs. security pressure', reasonZh: '宪法制约vs安全压力' },
        { countryId: 'IND', severity: 'medium', direction: 'negative', impactPercent: -6, reason: 'Forced into arms race; budget pressure', reasonZh: '被迫参加军备竞赛；预算压力' },
        { countryId: 'KOR', severity: 'low', direction: 'negative', impactPercent: -5, reason: 'Defense tech investment surge', reasonZh: '国防科技投资激增' },
      ],
      cityImpacts: [
        { cityId: 'washington-dc', severity: 'high', direction: 'negative', impactType: 'other' },
        { cityId: 'beijing', severity: 'high', direction: 'negative', impactType: 'other' },
        { cityId: 'san-francisco', severity: 'medium', direction: 'mixed', impactType: 'other' },
        { cityId: 'tel-aviv', severity: 'medium', direction: 'mixed', impactType: 'other' },
        { cityId: 'london', severity: 'medium', direction: 'negative', impactType: 'other' },
        { cityId: 'moscow', severity: 'medium', direction: 'negative', impactType: 'other' },
      ],
      activatedRelationships: [
        'USA-CHN-political', 'CHN-RUS-military_alliance', 'USA-GBR-military_alliance',
        'USA-JPN-military_alliance', 'USA-KOR-military_alliance', 'USA-ISR-military_alliance',
        'GBR-USA-political', 'CHN-IND-political',
      ],
      summary: 'An AI military arms race would divert trillions from civilian AI research to weapons development, risk autonomous weapons incidents, and create a new dimension of deterrence more unpredictable than nuclear weapons. The absence of AI arms control treaties makes escalation risks uniquely high.',
      summaryZh: 'AI军事军备竞赛将数万亿美元从民用AI研究转向武器研发，存在自主武器事件风险，并创造比核武器更不可预测的新威慑维度。缺乏AI军备控制条约使升级风险格外高。',
    },
  },
  {
    id: 'critical-infrastructure-cyberattack',
    name: 'Critical Infrastructure Cyber Attack',
    nameCn: '关键基础设施网络攻击',
    category: 'technology',
    description: 'Coordinated cyber attack targets power grids and financial systems.',
    descriptionZh: '协调的网络攻击针对电网和金融系统。',
    eventText: 'What if a coordinated cyber attack takes down power grids and financial systems?',
    keywords: ['cyber', 'attack', 'hack', 'infrastructure', 'power grid', 'ransomware', '网络', '攻击', '黑客', '基础设施', '电网', '勒索'],
    result: {
      event: 'Coordinated cyber attack on power grids and financial systems',
      timestamp: '2026-07-15T00:00:00Z',
      epicenter: { countryId: 'USA', coordinates: [-98.58, 39.83] },
      countryImpacts: [
        { countryId: 'USA', severity: 'critical', direction: 'negative', impactPercent: -30, reason: 'Power grid and financial systems down', reasonZh: '电网和金融系统瘫痪' },
        { countryId: 'GBR', severity: 'high', direction: 'negative', impactPercent: -20, reason: 'Financial center targeted; NHS disrupted', reasonZh: '金融中心被攻击；NHS中断' },
        { countryId: 'DEU', severity: 'high', direction: 'negative', impactPercent: -15, reason: 'Industrial control systems compromised', reasonZh: '工业控制系统被入侵' },
        { countryId: 'JPN', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Financial infrastructure attacked', reasonZh: '金融基础设施被攻击' },
        { countryId: 'FRA', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Nuclear plant control systems probed', reasonZh: '核电站控制系统被探测' },
        { countryId: 'KOR', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Digital infrastructure highly connected', reasonZh: '数字基础设施高度互联' },
        { countryId: 'CHN', severity: 'low', direction: 'mixed', impactPercent: -5, reason: 'Suspected origin; diplomatic fallout', reasonZh: '被怀疑为发起方；外交影响' },
        { countryId: 'RUS', severity: 'low', direction: 'mixed', impactPercent: -5, reason: 'Suspected origin; sanctions risk', reasonZh: '被怀疑为发起方；制裁风险' },
        { countryId: 'ISR', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'Retaliatory cyber operations launched', reasonZh: '发起报复性网络行动' },
      ],
      cityImpacts: [
        { cityId: 'new-york', severity: 'critical', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'washington-dc', severity: 'critical', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'london', severity: 'high', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'frankfurt', severity: 'high', direction: 'negative', impactType: 'market_crash' },
        { cityId: 'tokyo', severity: 'medium', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'tel-aviv', severity: 'medium', direction: 'negative', impactType: 'infrastructure_damage' },
      ],
      activatedRelationships: [
        'USA-GBR-military_alliance', 'USA-DEU-military_alliance', 'USA-JPN-military_alliance',
        'USA-KOR-military_alliance', 'USA-ISR-military_alliance',
        'RUS-GBR-political', 'USA-CHN-political', 'CHN-RUS-political',
      ],
      summary: 'A coordinated cyber attack on Western power grids and financial systems would cause cascading failures affecting hundreds of millions of people. With no physical destruction, attribution would be contested, making retaliation difficult and creating a dangerous escalation dilemma between cyber and kinetic warfare.',
      summaryZh: '对西方电网和金融系统的协调网络攻击将导致影响数亿人的级联故障。由于没有物理破坏，归因将受到争议，使报复变得困难，并在网络战和动能战之间创造危险的升级困境。',
    },
  },
  {
    id: 'undersea-cable-sabotage',
    name: 'Undersea Cable Sabotage',
    nameCn: '海底电缆破坏',
    category: 'technology',
    description: 'Multiple undersea internet cables simultaneously severed.',
    descriptionZh: '多条海底互联网电缆同时被切断。',
    eventText: 'What if multiple undersea internet cables are simultaneously severed?',
    keywords: ['undersea', 'cable', 'internet', 'sabotage', 'submarine', 'fiber', '海底', '电缆', '互联网', '破坏', '光纤'],
    result: {
      event: 'Multiple undersea internet cables simultaneously severed',
      timestamp: '2026-08-15T00:00:00Z',
      epicenter: { countryId: 'GBR', coordinates: [-5.0, 50.0] },
      countryImpacts: [
        { countryId: 'GBR', severity: 'critical', direction: 'negative', impactPercent: -25, reason: 'Island nation; internet connectivity severed', reasonZh: '岛国；互联网连接中断' },
        { countryId: 'USA', severity: 'high', direction: 'negative', impactPercent: -18, reason: 'Transatlantic data flows disrupted', reasonZh: '跨大西洋数据流中断' },
        { countryId: 'FRA', severity: 'high', direction: 'negative', impactPercent: -12, reason: 'European internet backbone damaged', reasonZh: '欧洲互联网骨干受损' },
        { countryId: 'DEU', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Financial data transmission disrupted', reasonZh: '金融数据传输中断' },
        { countryId: 'JPN', severity: 'medium', direction: 'negative', impactPercent: -10, reason: 'Pacific cable routes damaged', reasonZh: '太平洋电缆路线受损' },
        { countryId: 'SGP', severity: 'medium', direction: 'negative', impactPercent: -12, reason: 'Asia-Europe data hub disrupted', reasonZh: '亚欧数据枢纽中断' },
        { countryId: 'IND', severity: 'medium', direction: 'negative', impactPercent: -15, reason: 'IT outsourcing industry paralyzed', reasonZh: 'IT外包产业瘫痪' },
        { countryId: 'NOR', severity: 'medium', direction: 'negative', impactPercent: -8, reason: 'North Sea cables targeted', reasonZh: '北海电缆被攻击' },
      ],
      cityImpacts: [
        { cityId: 'london', severity: 'critical', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'new-york', severity: 'high', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'singapore', severity: 'high', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'bangalore', severity: 'high', direction: 'negative', impactType: 'infrastructure_damage' },
        { cityId: 'frankfurt', severity: 'medium', direction: 'negative', impactType: 'infrastructure_damage' },
      ],
      activatedRelationships: [
        'USA-GBR-trade', 'USA-GBR-military_alliance', 'GBR-FRA-trade',
        'GBR-FRA-military_alliance', 'DEU-GBR-trade', 'USA-IND-supply_chain',
        'SGP-MYS-trade', 'JPN-SGP-trade',
      ],
      summary: 'Simultaneous severing of major undersea cables would fragment the global internet, cutting financial data flows that process $10T/day in transactions. The UK, as an island dependent on cables, would face near-total internet isolation. India\'s $200B IT outsourcing industry would come to a standstill.',
      summaryZh: '同时切断主要海底电缆将分裂全球互联网，切断每天处理10万亿美元交易的金融数据流。英国作为依赖电缆的岛国将面临几乎完全的互联网隔离。印度2000亿美元的IT外包产业将陷入停滞。',
    },
  },
];
